Arseni-sprint1
ClevertecFrontendLab/sprint1-ars3nka pull request #1
Opened 2023-01-24 08:52 UTC by ars3nka

2023-01-24 08:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 6.
Количество непройденных тестов: 6.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 1440px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%201440px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674550482/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)

2023-01-25 13:09 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674652153/content-window.png)

2023-01-25 13:26 UTC, SergeyGlazun commented
проверь размеры карточки на 320 размеры

2023-01-25 17:04 UTC, SergeyGlazun commented
и цифры в списке что то скачут там де публицистическая литература и юмористическая

2023-01-26 08:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674720623/content-window.png)

2023-01-26 08:14 UTC, ars3nka commented
добрый, всё что заметил пофиксил, в целом по заданию вроде все сделал, буду рад любой критике и замечаниям

2023-01-26 08:49 UTC, Ivan6813 requested changes

2023-01-26 08:49 UTC, Ivan6813 commented on src/pages/main/components/menu/menu.jsx
> +        <MenuGenre genre='Юмористическая литература' amount={8} />
однотипные списки лучше выводить через map, то есть создавать в константах массив с данными и эти данные подставлять через map

2023-01-26 08:49 UTC, Ivan6813 commented on src/components/footer/footer.jsx
> +          </a>
однотипные списки лучше выводить через map, то есть создавать в константах массив с данными и эти данные подставлять через map

2023-01-26 08:49 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +      <main>
на скриншотах нет страницы с одной книгой, перепроверь это

2023-01-26 08:49 UTC, Ivan6813 commented on src/pages/main/components/books/books-list.jsx
> +
поправь немного вид карточек при мобильном разрешении, а то как-то не очень смотрятся)
![msedge_fBnBSzLGaR](https://user-images.githubusercontent.com/79784960/214793824-e15a8d45-fc81-46d2-ba25-4536dfeb7010.png)

2023-01-26 09:08 UTC, ars3nka commented on src/pages/book/book-page.jsx
> +      <main>
возможно с роутом дело, ссылка меняется в адресной строке, но чтобы увидеть загруженную страницу надо ее встручную обновить

2023-01-26 09:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674725764/content-window.png)

2023-01-26 09:37 UTC, ars3nka commented
переделал списки через map, исправил косяк на разрешении 320px,
но с роутом не разобрался у меня ссылка в адресной строке меняется но пока вручную не перезагрузишь ничего не появиятся, пока решил таким способом onClick={() => setTimeout(() => document.location.reload(), 100)}

2023-01-26 09:51 UTC, SergeyGlazun commented on src/pages/main/components/books/components/book/book.jsx
> +  <a href='/#/book' data-test-id='card' onClick={() => setTimeout(() => document.location.reload(), 100)}>
relod оч плохо по сути отменяет все концепцию, ты перегрузишь странницу а значит все будет перерисовываться и пере подтягиваться, а нужно что б только перерисовывался тот компонент который изменился а все остальное осталось без изменений, верстка это не просто отрисованные две страницы а еще и переключение между ними, в требованиях было обязательным использовать роуты, используй <NavLink to='/book' место <a ref

2023-01-26 09:54 UTC, ars3nka commented on src/pages/main/components/books/components/book/book.jsx
> +  <a href='/#/book' data-test-id='card' onClick={() => setTimeout(() => document.location.reload(), 100)}>
спасибо!! разобрался

2023-01-26 10:03 UTC, SergeyGlazun approved these changes

2023-01-26 10:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ars3nka/1674727391/content-window.png)

2023-01-26 10:28 UTC, Ivan6813 approved these changes

2023-01-26 11:46 UTC, merged